language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
#after_success:
#- if ( [ "$TRAVIS_BRANCH" == "master" ]  && [ "$TRAVIS_REPO_SLUG" == "dhis2/tracker-capture-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
#        mvn clean deploy --settings deploy/settings.xml && exit 0;
#  fi
